title: 'R Exposure'
description: "Course website for R Exposure 3 & 4"
logo: 'https://raw.githubusercontent.com/clanfear/CSSS508/master/docs/img/csss_white.png'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal